sonar.projectName=PHP Domain Events
sonar.projectKey=ComplexHeart_php-domain-events
sonar.organization=complexheart
sonar.language=php
sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=test.xml
